### ISSUE TITLE
Miniature dans espace membre

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/image-heberg.fr#11]
Miniature de l'image dans l'espace membre

**Comment by NuggaN85** [comment]
salut,
possible pour le png a font transparent mettre le font en blanc et non en noir car pour du png sa fait très moche ^^

**Comment by AnaelMobilia** [comment]
Bonne idée !
Voir https://www.php.net/manual/en/function.imagecolortransparent.php#example-3785 pour l'implémentation

**Comment by AnaelMobilia** [comment]
Closed by aa6f0fccd0d163923e8202742e8834cf312b5e22
