### ISSUE TITLE
Problème après installation

### ISSUE THREAD

**Issue by NuggaN85** [AnaelMobilia/image-heberg.fr#20]
Petit problème après installation dans 

> public_html/classes/sessionObject.class.php on line 32
et dans statistique Warning: Division by zero in 

Problème aussi dans le fichier stats
> public_html/stats.php on line 63 

test de upload marcche pas non plus 

> Une erreur a été rencontrée !
> La page n'a pas été appelée correctement.

et les identifiant admin / password ne marche pas non plus.

version PHP 7.2 plus PHP-FPM => MySQL INNODB

**Comment by NuggaN85** [comment]
@AnaelMobilia j'ai pas de log erreur voici mon lien pour voir les erreurs qui on été mentionner.
https://www.image-heberg.weax.net/

**Comment by NuggaN85** [comment]
Warning: session_start(): Cannot start session when headers already sent in /home/imageheberg/public_html/classes/sessionObject.class.php on line 32

**Comment by NuggaN85** [comment]
ail ail ail il est bourrer de bug même en créent un compte.

> Warning: Cannot modify header information - headers already sent by (output started at /home/imageheberg/public_html/template/templateV2Top.php:22) in /home/imageheberg/public_html/membre/creerCompte.php on line 79

**Comment by AnaelMobilia** [comment]
@NuggaN85 Pour la partie open-source, le code est accessible, libre à chacun de corriger et de proposer une pull-request. Comme on peut le voir dans les contributors, personne n'a pris le temps de le faire... :-)
Le script fonctionne puisqu'il est en production depuis plusieurs années (ce dépôt est le partage de mon code source ;-)).

Je pense qu'il y a une erreur de configuration au niveau du serveur : les entêtes ont déjà été envoyés avant que le script ne soit appelé... Ce qui remet en question la gestion des sessions donc du programme en entier.

Ca rejoint #18 du coup :-)

**Comment by NuggaN85** [comment]
@AnaelMobilia ben sais super pour ceux qui connais rien et j'ai 2 gros site avec le système de session_start() et vous êtes le seule qui bug donc bon pas grave j'attendais cette réponse pour virer ce script de mon serveur merci quand même.

**Comment by NuggaN85** [comment]
Pas de close sa peux servir pour les autres
