### ISSUE TITLE
illogisme affichage upload

### ISSUE THREAD

**Issue by AnaelMobilia** [AnaelMobilia/image-heberg.fr#31]
![image](https://user-images.githubusercontent.com/6187125/69582836-b6f43900-0fd9-11ea-8f8c-1d3aea35cc00.png)

**Comment by NuggaN85** [comment]
salut sur mobile il y a un bug avec le lien direct http://image-heberg.weax.net/files/15784820491822050041.jpg et j'ai vus aussi que tu as pas fait la maj pour ceci https://github.com/AnaelMobilia/image-heberg.fr/issues/12#issuecomment-557232724

et aussi pour le font noir mettre en font blanc pour les png transparent car en noir sa fait très moche et on vois rien :)

**Comment by AnaelMobilia** [comment]
Nom du fichier envoyé erroné => l'affichage a raison, il s'agit bien d'un fichier PNG !
